/*
Este schema está desativado no demo local. Para reativar o Supabase,
remova este comentário de bloco e execute o arquivo no SQL Editor.

-- Execute no SQL Editor do Supabase antes de ativar o modo de produção.
create extension if not exists pgcrypto;

create table if not exists categories(id bigint generated by default as identity primary key, name text unique not null, created_at timestamptz default now());
create table if not exists suppliers(id bigint generated by default as identity primary key, name text unique not null, created_at timestamptz default now());
create table if not exists products(id bigint generated by default as identity primary key, name text unique not null, category_id bigint references categories(id), supplier_id bigint references suppliers(id), unit text default 'kg', stock numeric default 0, min_stock numeric default 10, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists stock_movements(id uuid primary key default gen_random_uuid(), product_id bigint references products(id) not null, type text check(type in ('entrada','saida','ajuste')) not null, quantity numeric not null, previous_stock numeric, new_stock numeric, movement_date date default current_date, note text, user_id uuid references auth.users(id), created_at timestamptz default now());
create table if not exists balance_movements(id uuid primary key default gen_random_uuid(), product_id bigint references products(id) not null, type text check(type in ('entrada','saida')) not null, quantity numeric not null, movement_date date default current_date, note text, user_id uuid references auth.users(id), created_at timestamptz default now());
alter table balance_movements add column if not exists performed_by text;
alter table balance_movements add column if not exists unit_price numeric default 0;
alter table balance_movements add column if not exists document_number text;
alter table stock_movements add column if not exists performed_by text;
alter table stock_movements add column if not exists unit_price numeric default 0;
alter table stock_movements add column if not exists document_number text;
alter table stock_movements add column if not exists attachment_path text;
alter table stock_movements add column if not exists attachment_name text;
drop function if exists register_stock_movement(uuid, bigint, text, numeric, date, text, numeric, uuid, text);
create table if not exists audit_logs(id bigint generated by default as identity primary key, user_id uuid references auth.users(id), performed_by text not null, action text not null, entity_type text not null, entity_id text, details text, created_at timestamptz default now());
create table if not exists balance_contracts(id bigint generated by default as identity primary key, product_id bigint references products(id) not null, supplier_id bigint references suppliers(id), ordered_quantity numeric not null, unit_price numeric default 0, contract_date date, note text, created_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now(), unique(product_id));
create table if not exists orders(id bigint generated by default as identity primary key, product_id bigint references products(id), supplier_id bigint references suppliers(id), ordered_quantity numeric not null, reference text, created_at timestamptz default now());
create table if not exists receipts(id bigint generated by default as identity primary key, order_id bigint references orders(id), receipt_date date not null, quantity numeric not null, invoice_number text, user_id uuid references auth.users(id), created_at timestamptz default now());
create or replace function register_stock_movement(p_movement_id uuid, p_product_id bigint, p_type text, p_quantity numeric, p_movement_date date, p_note text, p_unit_price numeric, p_document_number text, p_user_id uuid, p_performed_by text)
returns table(previous_stock numeric, new_stock numeric)
language plpgsql
security invoker
set search_path = public
as $$
declare
	current_stock numeric;
	updated_stock numeric;
begin
	if p_quantity is null or p_quantity <= 0 then
		raise exception 'Informe uma quantidade válida.';
	end if;
	select stock into current_stock from products where id = p_product_id and active = true for update;
	if not found then
		raise exception 'Produto não encontrado ou inativo.';
	end if;
	updated_stock := case when p_type = 'entrada' then current_stock + p_quantity when p_type = 'saida' then current_stock - p_quantity when p_type = 'ajuste' then p_quantity else null end;
	if updated_stock is null then
		raise exception 'Tipo de movimentação inválido.';
	end if;
	if updated_stock < 0 then
		raise exception 'Quantidade indisponível. O saldo atual deste produto é de %.', current_stock;
	end if;
	insert into stock_movements(id, product_id, type, quantity, previous_stock, new_stock, movement_date, note, unit_price, document_number, user_id, performed_by)
	values (p_movement_id, p_product_id, p_type, p_quantity, current_stock, updated_stock, coalesce(p_movement_date, current_date), p_note, coalesce(p_unit_price, 0), p_document_number, p_user_id, coalesce(p_performed_by, 'Autor não informado'));
	update products set stock = updated_stock, updated_at = now() where id = p_product_id;
	return query select current_stock, updated_stock;
end;
$$;
grant execute on function register_stock_movement(uuid, bigint, text, numeric, date, text, numeric, text, uuid, text) to authenticated;
insert into storage.buckets (id, name, public) values ('movement-attachments', 'movement-attachments', false) on conflict (id) do nothing;
drop policy if exists "authenticated users can read movement attachments" on storage.objects;
create policy "authenticated users can read movement attachments" on storage.objects for select to authenticated using (bucket_id = 'movement-attachments');
drop policy if exists "authenticated users can upload movement attachments" on storage.objects;
create policy "authenticated users can upload movement attachments" on storage.objects for insert to authenticated with check (bucket_id = 'movement-attachments');
drop policy if exists "authenticated users can delete movement attachments" on storage.objects;
create policy "authenticated users can delete movement attachments" on storage.objects for delete to authenticated using (bucket_id = 'movement-attachments');
-- Exemplo de RLS: em produção, crie políticas específicas para as duas usuárias autorizadas.
alter table categories enable row level security;
alter table suppliers enable row level security;
alter table products enable row level security;
alter table stock_movements enable row level security;
alter table balance_movements enable row level security;
alter table orders enable row level security;
alter table receipts enable row level security;
alter table audit_logs enable row level security;
alter table balance_contracts enable row level security;

-- Esta política permite acesso somente a pessoas autenticadas no Supabase Auth.
-- Para restringir por e-mail ou domínio, substitua auth.uid() por uma tabela de perfis.
drop policy if exists "authenticated users can read categories" on categories;
create policy "authenticated users can read categories" on categories for select to authenticated using (true);
drop policy if exists "authenticated users can manage categories" on categories;
create policy "authenticated users can manage categories" on categories for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read suppliers" on suppliers;
create policy "authenticated users can read suppliers" on suppliers for select to authenticated using (true);
drop policy if exists "authenticated users can manage suppliers" on suppliers;
create policy "authenticated users can manage suppliers" on suppliers for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read products" on products;
create policy "authenticated users can read products" on products for select to authenticated using (true);
drop policy if exists "authenticated users can manage products" on products;
create policy "authenticated users can manage products" on products for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read movements" on stock_movements;
create policy "authenticated users can read movements" on stock_movements for select to authenticated using (true);
drop policy if exists "authenticated users can insert movements" on stock_movements;
create policy "authenticated users can insert movements" on stock_movements for insert to authenticated with check (true);
drop policy if exists "authenticated users can update movement attachments" on stock_movements;
create policy "authenticated users can update movement attachments" on stock_movements for update to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read balance movements" on balance_movements;
create policy "authenticated users can read balance movements" on balance_movements for select to authenticated using (true);
drop policy if exists "authenticated users can insert balance movements" on balance_movements;
create policy "authenticated users can insert balance movements" on balance_movements for insert to authenticated with check (true);
drop policy if exists "authenticated users can read orders" on orders;
create policy "authenticated users can read orders" on orders for select to authenticated using (true);
drop policy if exists "authenticated users can manage orders" on orders;
create policy "authenticated users can manage orders" on orders for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read receipts" on receipts;
create policy "authenticated users can read receipts" on receipts for select to authenticated using (true);
drop policy if exists "authenticated users can manage receipts" on receipts;
create policy "authenticated users can manage receipts" on receipts for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users can read audit logs" on audit_logs;
create policy "authenticated users can read audit logs" on audit_logs for select to authenticated using (true);
drop policy if exists "authenticated users can insert audit logs" on audit_logs;
create policy "authenticated users can insert audit logs" on audit_logs for insert to authenticated with check (true);
drop policy if exists "authenticated users can read balance contracts" on balance_contracts;
create policy "authenticated users can read balance contracts" on balance_contracts for select to authenticated using (true);
drop policy if exists "authenticated users can manage balance contracts" on balance_contracts;
create policy "authenticated users can manage balance contracts" on balance_contracts for all to authenticated using (true) with check (true);

-- Habilita a entrega de alterações para todas as abas e usuários conectados.
do $$
begin
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'categories') then alter publication supabase_realtime add table categories; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'suppliers') then alter publication supabase_realtime add table suppliers; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products') then alter publication supabase_realtime add table products; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'stock_movements') then alter publication supabase_realtime add table stock_movements; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'balance_movements') then alter publication supabase_realtime add table balance_movements; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders') then alter publication supabase_realtime add table orders; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'receipts') then alter publication supabase_realtime add table receipts; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'audit_logs') then alter publication supabase_realtime add table audit_logs; end if;
	if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'balance_contracts') then alter publication supabase_realtime add table balance_contracts; end if;
end $$;
*/
