const groups = {
    'CCF NUTRI': ['SUCO DE LARANJA', 'REQUEIJÃO CREMOSO'],
    FEC: ['AMIDO DE MILHO', 'ARROZ INTEGRAL', 'AVEIA EM FLOCOS', 'AVEIA EM FARINHA', 'CANJICA', 'COCO RALADO', 'DOCE DE LEITE', 'FEIJÃO BRANCO', 'KIT LANCHE', 'LEITE DE COCO', 'MACARRÃO DE ARROZ', 'PÃO SEM GLÚTEN', 'PÁPRICA DEFUMADA', 'QUIRELA', 'VINAGRE', 'ERVILHA', 'FARINHA DE TRIGO', 'FEIJÃO CARIOCA'],
    FRIGOBOI: ['MÚSCULO CUBOS', 'PATINHO CUBOS', 'PATINHO ISCAS', 'PATINHO MOIDO', 'PERNIL CUBOS', 'SOBRECOXA CUBOS', 'PEITO CUBOS'],
    'MERCADO CENTRAL': ['AÇUCAR', 'EXTRATO DE TOMATE', 'MACARRÃO LETRINHA', 'MACARRÃO PARAFUSO', 'ÓLEO GIRASSOL', 'ALFACE', 'MUSSARELA'],
    SENGÉS: ['ACHOCOLATADO DIET', 'ARROZ', 'BISCOITO DOCE', 'CHÁ CAMOMILA', 'FEIJÃO PRETO', 'FERMENTO BIOLÓGICO', 'LEITE EM PÓ', 'LEITE ZERO LACTOSE', 'LOURO', 'MANTEIGA EXTRA', 'MINI PIZZA', 'REQUEIJÃO ZERO LACTOSE', 'TRIGO KIBE'],
    STS: ['ADOÇANTE', 'BISCOITO SEM LACTOSE', 'BISCOITO CREAM CRACKER', 'CHÁ ERVA DOCE', 'CHOCOLATE 50%', 'FARINHA DE ARROZ', 'FERMENTO QUÍMICO', 'MACARRÃO AVE MARIA', 'MACARRÃO PENNE', 'MILHO VERDE', 'ORÉGANO', 'SAL', 'ALHO', 'ÓLEO SOJA'],
    'DA ROÇA': ['ABACATE', 'BANANA NANICA', 'BANANA PRATA', 'MEXERICA', 'MORANGO', 'PEPINO', 'PITAYA', 'ABACAXI', 'ABÓBORA PESCOÇO', 'ABOBRINHA', 'BATATA INGLESA', 'LARANJA', 'LIMÃO', 'MAMÃO', 'MANDIOQUINHA SALSA', 'MELANCIA', 'OVOS', 'TOMATE'],
    'QUITANDA FRUTASOL': ['MAÇA', 'MANDIOCA', 'PERA'],
    AGROVIDA: ['ABOBRINHA', 'ABÓBORA PESCOÇO', 'ALFACE', 'BATATA DOCE', 'BETERRABA', 'BRÓCOLIS', 'CEBOLA', 'CEBOLINHA', 'CENOURA', 'COUVE', 'COUVE-FLOR', 'MANDIOCA', 'MELANCIA', 'MILHO VERDE', 'PEPINO', 'REPOLHO', 'SALSINHA'],
    COOPAFASP: ['ABOBRINHA', 'ABACATE', 'ABÓBORA PESCOÇO', 'ACELGA', 'ALFACE', 'BANANA NANICA', 'BANANA PRATA', 'BATATA DOCE', 'BETERRABA', 'BRÓCOLIS', 'CEBOLA', 'CEBOLINHA', 'CENOURA', 'CHUCHU', 'COUVE', 'COUVE-FLOR', 'ESPINAFRE', 'LARANJA', 'LIMÃO', 'MANDIOCA', 'MELANCIA', 'MEXERICA', 'MILHO VERDE', 'PEPINO', 'PITAYA', 'REPOLHO', 'SALSINHA', 'TOMATE'],
    'AGUA PRETA': ['LEITE', 'MANTEIGA', 'REQUEIJÃO'],
    'DA TERRA': ['FEIJÃO CARIOCA'],
    ELCILAINE: ['MANJERIÇÃO', 'SALSINHA', 'CEBOLINHA'],
    FRANCISCO: ['MANJERIÇÃO', 'SALSINHA', 'CEBOLINHA'],
    'LUIZ RAFAEL': ['MAMÃO FORMOSO'],
    MAURICIO: ['MAMÃO FORMOSO'],
    'MARCIA CORREA': ['MAÇÃ'],
    REGINALDO: ['MAÇÃ'],
    'PEDRO GERALDO': ['MAÇÃ'],
    'HORÁCIO': ['MAÇÃ']
};

const categoryFor = name => ['HORTIFRUTI', 'FRUTAS', 'VERDURAS'].some(word => name.includes(word)) ? 'Hortifruti' : ['LEITE', 'MANTEIGA', 'REQUEIJÃO', 'MUSSARELA', 'DOCE DE LEITE'].some(word => name.includes(word)) ? 'Laticínios' : name.includes('CUBOS') || name.includes('ISCA') || name.includes('MUSCULO') || name.includes('PATINHO') || name.includes('PERNIL') || name.includes('SOBRECOXA') || name.includes('PEITO') ? 'Carnes' : 'Alimentos Secos';

export const catalogProducts = Object.entries(groups).flatMap(([supplier, names]) => names.map(name => ({ name, category: categoryFor(name), supplier, unit: name === 'LEITE' ? 'L' : 'kg' }))).sort((a, b) => a.name.localeCompare(b.name, 'pt-BR')).map((product, index) => ({ ...product, id: index + 1, stock: 0, minStock: 10 }));
